name: DEPLOY

on:
  push:
    branches:
      - terra-deploy
  pull_request:
    branches:
      - terra-deploy

env:
  REACT_APP_CLUSTER: ${{ secrets.CLUSTER }}
  REACT_APP_COVALENT_API_KEY: ${{ secrets.COVALENT_API_KEY }}
  REACT_APP_SOLANA_API_URL: https://wormhole.rpcpool.com/
  
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Rust cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build --target node-export -f Dockerfile.proto -o type=local,dest=. .
          DOCKER_BUILDKIT=1 docker build -f solana/Dockerfile.wasm -o type=local,dest=. solana
          npm ci --prefix ethereum
          npm ci --prefix sdk/js
          npm run build --prefix sdk/js
          npm ci --prefix bridge_ui
          npm ci --prefix lp_ui
          npm run build --prefix bridge_ui
          npm run build --prefix lp_ui
          ls -al bridge_ui
          ls -al lp_ui

      - name: Deploy bridge_ui
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: terra-money/wormhole-bridge-ui
          publish_branch: main
          publish_dir: ./bridge_ui/build

      - name: Deploy lp_ui
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: terra-money/wormhole-lp-ui
          publish_branch: main
          publish_dir: ./lp_ui/build
